In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

from glob import glob

import librosa
import librosa.display
import IPython.display as ipd

In [117]:
audio_files_m4a = glob('/Users/d0304693/Documents/fun/als-voice-cloning-evaluation/data/m4a/*.m4a')
print(len(audio_files_m4a))

42

In [118]:
data_frame_m4a = []

In [120]:
for f in audio_files_m4a:
    y, sr = librosa.load(f)
    data_frame_m4a.append({
        'file': f,
        'duration_s': librosa.get_duration(y=y, sr=sr),
        'sample_rate': sr,
        'num_samples': len(y),
        'file_format': f.split('.')[-1],
    })
df = pd.DataFrame(data_frame_m4a)

/var/folders/h9/hvhggy7d0dq_2zmy_gbx1n_r0000gp/T/ipykernel_92240/240927522.py:2: UserWarning: PySoundFile failed. Trying audioread instead.
  y, sr = librosa.load(f)
/Users/d0304693/Library/Python/3.13/lib/python/site-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

In [121]:
df

,file,duration_s,sample_rate,num_samples,file_format
0,/Users/d0304693/Documents/fun/als-voice-clonin...,38.82,22050,855981,m4a
1,/Users/d0304693/Documents/fun/als-voice-clonin...,41.94,22050,924777,m4a
2,/Users/d0304693/Documents/fun/als-voice-clonin...,93.06,22050,2051973,m4a
3,/Users/d0304693/Documents/fun/als-voice-clonin...,15.22,22050,335601,m4a
4,/Users/d0304693/Documents/fun/als-voice-clonin...,15.64,22050,344862,m4a
5,/Users/d0304693/Documents/fun/als-voice-clonin...,31.26,22050,689283,m4a
6,/Users/d0304693/Documents/fun/als-voice-clonin...,16.98,22050,374409,m4a
7,/Users/d0304693/Documents/fun/als-voice-clonin...,152.60,22050,3364830,m4a
8,/Users/d0304693/Documents/fun/als-voice-clonin...,34.62,22050,763371,m4a
9,/Users/d0304693/Documents/fun/als-voice-clonin...,88.84,22050,1958922,m4a
10,/Users/d0304693/Documents/fun/als-voice-clonin...,24.00,22050,529200,m4a
11,/Users/d0304693/Documents/fun/als-voice-clonin...,20.28,22050,447174,m4a
12,/Users/d0304693/Documents/fun/als-voice-clonin...,81.02,22050,1786491,m4a
13,/Users/d0304693/Documents/fun/als-voice-clonin...,40.20,22050,886410,m4a
14,/Users/d0304693/Documents/fun/als-voice-clonin...,67.70,22050,1492785,m4a
15,/Users/d0304693/Documents/fun/als-voice-clonin...,23.62,22050,520821,m4a
16,/Users/d0304693/Documents/fun/als-voice-clonin...,80.68,22050,1778994,m4a
17,/Users/d0304693/Documents/fun/als-voice-clonin...,41.72,22050,919926,m4a
18,/Users/d0304693/Documents/fun/als-voice-clonin...,23.22,22050,512001,m4a
19,/Users/d0304693/Documents/fun/als-voice-clonin...,26.02,22050,573741,m4a
20,/Users/d0304693/Documents/fun/als-voice-clonin...,38.14,22050,840987,m4a
21,/Users/d0304693/Documents/fun/als-voice-clonin...,25.32,22050,558306,m4a
22,/Users/d0304693/Documents/fun/als-voice-clonin...,51.30,22050,1131165,m4a
23,/Users/d0304693/Documents/fun/als-voice-clonin...,18.80,22050,414540,m4a
24,/Users/d0304693/Documents/fun/als-voice-clonin...,24.94,22050,549927,m4a
25,/Users/d0304693/Documents/fun/als-voice-clonin...,43.40,22050,956970,m4a
26,/Users/d0304693/Documents/fun/als-voice-clonin...,24.38,22050,537579,m4a
27,/Users/d0304693/Documents/fun/als-voice-clonin...,35.24,22050,777042,m4a
28,/Users/d0304693/Documents/fun/als-voice-clonin...,46.54,22050,1026207,m4a
29,/Users/d0304693/Documents/fun/als-voice-clonin...,47.10,22050,1038555,m4a
30,/Users/d0304693/Documents/fun/als-voice-clonin...,76.10,22050,1678005,m4a
31,/Users/d0304693/Documents/fun/als-voice-clonin...,79.14,22050,1745037,m4a
32,/Users/d0304693/Documents/fun/als-voice-clonin...,13.82,22050,304731,m4a
33,/Users/d0304693/Documents/fun/als-voice-clonin...,19.50,22050,429975,m4a
34,/Users/d0304693/Documents/fun/als-voice-clonin...,94.66,22050,2087253,m4a
35,/Users/d0304693/Documents/fun/als-voice-clonin...,63.58,22050,1401939,m4a
36,/Users/d0304693/Documents/fun/als-voice-clonin...,20.42,22050,450261,m4a
37,/Users/d0304693/Documents/fun/als-voice-clonin...,46.34,22050,1021797,m4a
38,/Users/d0304693/Documents/fun/als-voice-clonin...,25.20,22050,555660,m4a
39,/Users/d0304693/Documents/fun/als-voice-clonin...,41.70,22050,919485,m4a
40,/Users/d0304693/Documents/fun/als-voice-clonin...,21.90,22050,482895,m4a
41,/Users/d0304693/Documents/fun/als-voice-clonin...,43.14,22050,951237,m4a

In [122]:
df.describe()

       duration_s  sample_rate   num_samples
count   42.000000         42.0  4.200000e+01
mean    44.240476      22050.0  9.755025e+05
std     28.937217          0.0  6.380656e+05
min     13.820000      22050.0  3.047310e+05
25%     23.715000      22050.0  5.229158e+05
50%     38.480000      22050.0  8.484840e+05
75%     50.250000      22050.0  1.108012e+06
max    152.600000      22050.0  3.364830e+06